# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!
target 'Senior6th_NaverAPI' do

    pod 'Alamofire'
    pod 'SwiftyJSON'
#    pod 'Kingfisher'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'
end
