# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PTJ5_BoxOffice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PTJ5_BoxOffice
pod 'Cosmos', '~> 16.0'

end
