# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# pod install == pod update
# save 꼭 하고 난 뒤에 !
# 수정중일때는 podfile 색깔이 까망색 -> 수정완료 하양색

platform :ios, '9.0'
use_frameworks!

target 'Senior5th_cocoapod' do

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'
    pod 'ButtonBackgroundColor'
    
end
